---
# handlers file for teleport_update
- name: Check if systemctl daemon-reload is required
  command: systemctl status teleport
  register: systemctl_output
  # changed_when: false
  # failed_when: false

- name: Reload systemd daemon
  command: systemctl daemon-reload
  when: "'systemctl daemon-reload' in systemctl_output.stderr"
