---
# handlers file for teleport_update
- name: Restart Teleport service
  systemd:
    name: teleport
    state: restarted
  when: teleport_service_enabled | default(false)
  register: teleport_service_result

- name: Restart {{ second_service_name }} service
  systemd:
    name: "{{ second_service_name }}"
    state: restarted
  when: teleport_service_enabled and second_service_enabled
  register: second_service_result