---
dependency:
  name: galaxy
driver:
  name: podman
  podman_timeout: 300
platforms:
  - name: instance
    image: ubuntu:20.04
    dockerfile: Dockerfile
provisioner:
  name: ansible
verifier:
  name: ansible